# Generated by Django 2.2.6 on 2019-10-22 01:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=12)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_oprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goods_cprice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('goods_count', models.IntegerField()),
                ('goods_desc', models.CharField(max_length=128)),
                ('goods_detail', ckeditor.fields.RichTextField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='GoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=128)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.GoodType'),
        ),
    ]
